services:
  node:
    container_name: node
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000

  python:
    container_name: python
    build:
      dockerfile: Dockerfile
    ports:
      - 5001:5001